import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid min-h-screen place-items-center">
        <header className="flex flex-col gap-8 text-center">
          <div>
            <h1 className="mb-3 text-5xl font-bold md:text-7xl">
              ClipCollections
            </h1>
            <p className="font-semibold text-zinc-400">
              Organise your Twitch clips into collections for easier chat
              commands
            </p>
          </div>

          <div className="flex justify-center">
            <Link
              href={"/login"}
              className="text-md rounded-lg bg-gray-800 px-5 py-2.5 font-medium text-white hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700"
            >
              Create collection
            </Link>
          </div>
        </header>
      </main>
    </>
  );
};

export default Home;
